### ISSUE TITLE
Support for non-sqlite dbs

### ISSUE THREAD

**Issue by AntonOfTheWoods** [mphilli/English-to-IPA#11]
I'm very interested in using this but my app is multi-threaded so can't really use sqlite. I am going to add support for Postgres for my own purposes but if you would be interested in merging generic DB support then I can try and make it work for other flavours too. If you are interested I'll submit a PR.

**Comment by mphilli** [comment]
That does sound interesting; it would be one of the first major contributions to the project.

**Comment by jjtg** [comment]
I was having the same problem a few minutes ago. Since I am only using transcribe, I could solve it by creating a new connection within the fetch_words function and making it use that cursor. Works as a quick fix. I'd like to see support for other DB flavors though.

**Comment by AntonOfTheWoods** [comment]
Ok, that will teach me for opening my mouth... :-). 

Actually it may be a little more complicated than just implementing other DB support. At least in that my own usage patterns won't really fit. After thinking about it, I only need fully stress-marked IPA, which I will then load into a cache. Actually reprocessing for each time it gets called is simply a useless CO2 generator. So something that exports to very generic SQL would be a better fit in theory (I actually want it as K/V with V in JSON). Implementing proper, generic SQL support that made sense would be quite a lot of work... Seeing as my use case really doesn't need full support, and just ripping off your code works, others may be in the same situation and it may not be worth the extra hassle. What do you think?

I did have another question - it looks like there are some values that don't correspond to https://en.wikipedia.org/wiki/ARPABET - is there a reason for that? From looking quickly it seems there is a 1:1 correspondance so I can just change to the official ARPABET form but I'm interested to know whether that is intentional or not. So far I found only EY -> e vs. EY -> eɪ.

**Comment by mphilli** [comment]
@AntonOfTheWoods Don't worry about it, I thought that adding support for some sort of interaction with the CMU data besides SQL was a great idea, especially in light of the issue with your multi-threaded app.

I've added the ability to use JSON to interact with the data instead of SQL. It's not Postgres, but maybe we could add that at some point. 

My eventual plan to support multiple database types would be to overhaul the program to be *object-oriented*, writing a `Transcriber` class, where the database type can be easily specified and changed: 

```Python 
transcribe = Transcriber(db_type="Postgres")
transcribe.convert("some text") 
# switch database type
transcribe.db_type = "sqlite3"
transcribe.convert("some more text")
```

I'm not sure how to address your additional ARPABET issue. Maybe open a new issue for that and I will give it more attention if needed.

**Comment by AntonOfTheWoods** [comment]
Thanks @mphilli , I will have a need for a tool like this for the next few years but I don't know all the use-cases yet, so don't know all the features I'll need to implement. I'll be back though!

I opened https://github.com/mphilli/English-to-IPA/issues/12 for the ARBABET issue.
