### ISSUE TITLE
how can i get all the IPA symbols?

### ISSUE THREAD

**Issue by ArtemisZGL** [mphilli/English-to-IPA#15]
Hello, thanks for your great work ! I'm a little confused about the symbols of DJ, KK and IPA Phonetic Alphabet. And I found not all IPA symbols was used in English, so could you please show all the symbols used in this tool?

**Comment by mphilli** [comment]
A decent portion of the symbols can be found on [line #106](https://github.com/mphilli/English-to-IPA/blob/master/eng_to_ipa/transcribe.py#L106) of the `transcibe.py` file. Here are the IPA symbols repeated here: 

```Python
{"ə","eɪ", "ɑ", "æ", "ə", "ɔ", "aʊ", "aɪ", "ʧ", "ð", "ɛ", "ər", "h",
 "ɪ", "ʤ", "ŋ", "oʊ", "ɔɪ", "ʃ", "θ", "ʊ", "u", "ʒ", "i", "j"}
```

You'll notice some are missing here, though, mainly consonants. That's because the program converts the [CMU Pronouncing Dictionary](http://www.speech.cs.cmu.edu/cgi-bin/cmudict), which is in [ARPABET notation](https://en.wikipedia.org/wiki/ARPABET), to IPA, and specifying the IPA symbols is unnecessary if they are the same, e.g. `p → p`. 

So, this program does not *precisely* tell you all of the IPA symbols being used.

**Comment by ArtemisZGL** [comment]
@mphilli, thanks for your reply, I have one more question. How can I split the symbols in one word? As a result of the word "drawing" is "drɔɪŋ", and it can be confusing about "d r ɔ ɪ ŋ" and "d r ɔɪ ŋ".

**Comment by mphilli** [comment]
Maybe I'd need to understand better why you'd want to do that, but if you had an approved list of symbols that you wanted to potentially keep together, then you could create a function like this:

```Python
def split_word(ipa_word):

    together = ['ɔɪ'] # add more here
    together_space = [' '.join(list(i)) for i in together]

    split_ipa = ' '.join(list(ipa_word))

    for item in together_space:
        split_ipa = split_ipa.replace(item, item.replace(' ', ''))

    return split_ipa

print(split_word("drɔɪŋ"))
# prints 'd r ɔɪ ŋ'
```
